MVC/PurpleBuzzAreaCrud/PurpleBuzzProject/Areas/Admin/Controllers/ServiceAdminController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PurpleBuzzProject.DAL;
using PurpleBuzzProject.Models;

namespace PurpleBuzzProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ServiceAdminController : Controller
    {
        readonly AppDbContext _context;

        public ServiceAdminController(AppDbContext context)
        {
            _context = context;
        }

        public  IActionResult Index()
        {
            IEnumerable<OurService> ourServices =  _context.OurServices.ToList();
            return View(ourServices);
        }
        public IActionResult Delete(int Id)
        {
            OurService? deleteOurWork = _context.OurServices.Find(Id);
            if (deleteOurWork == null)
            {
                return NotFound();
            }
            else
            {
                _context.OurServices.Remove(deleteOurWork);
            }
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
           
        }
        public IActionResult Create()
        {
            
            return View();
        }
        [HttpPost]
        public IActionResult Create(OurService ourService)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest("smth went wrong");
            }
            else
            {
                _context.OurServices.Add(ourService);
                _context.SaveChanges();
            }

            
            return RedirectToAction(nameof(Index));
        }
        //burda update'in get sorgusu aparilir
        public IActionResult Update(int Id)
        {
           OurService? ourService = _context.OurServices.Find(Id);
            if (ourService == null)
            {
                return NotFound("No such Service");
            }

            return View(ourService);
        }
        [HttpPost]
        public IActionResult Update(OurService ourservice)
        {
          OurService? updateOurservice = _context.OurServices.AsNoTracking().FirstOrDefault(x=>x.Id == ourservice.Id);
            if (updateOurservice == null)
            {
                return NotFound("No Such Service");
            }
            _context.OurServices.Update(ourservice);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

    }
}

MVC/PurpleBuzzAreaCrud/PurpleBuzzProject/Areas/Admin/Views/ServiceAdmin/Index.cshtml
@model IEnumerable<OurService>


<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Tables</h1>
    

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Services</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">

                <a class=" btn btn-success  mb-3 mt-3" asp-area="Admin" asp-controller="ServiceAdmin" asp-action="Create">Create</a>

                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Title</th>
                            <th>Description</th>
                            <th>Image</th>
                            <th>Update</th>
                            <th>Delete</th>
                            
                            
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>ID</th>
                            <th>Title</th>
                            <th>Description</th>
                            <th>Image</th>
                            <th>Update</th>
                            <th>Delete</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        @foreach(OurService item in Model)
                        {
                            <tr>
                                <td>@item.Id</td>
                                <td>@item.Title</td>
                                <td>@item.Description</td>
                                <td> <img src="~/img/@item.ImgUrl" width="80" alt="img error"/></td>
                                <td> <a class="btn btn-success" asp-area="Admin" asp-controller="ServiceAdmin" asp-action="Update" asp-route-id="@item.Id">Update</a></td>
                                <td> <a class="btn btn-danger" asp-area="Admin" asp-controller="ServiceAdmin" asp-action="Delete" asp-route-Id="@item.Id">Delete</a></td>
                            </tr>
                        }

                      
                        
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->

MVC/PurpleBuzzAreaCrud/PurpleBuzzProject/Areas/Admin/Views/ServiceAdmin/create.cshtml
 @model OurWork;
 
    
    <form method="post">
        <div class="form-group">
            <label asp-for="Title"></label>
            <input class="form-control" asp-for="Title">
        </div>
        <div class="form-group">
            <label asp-for="Description"></label>
            <input class="form-control" asp-for="Description">
        </div>
        <div class="form-group">
            <label asp-for="ImgUrl"></label>
            <input class="form-control" asp-for="ImgUrl">
        </div>
 
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

MVC/PurpleBuzzAreaCrud/PurpleBuzzProject/Areas/Admin/Views/ServiceAdmin/update.cshtml
 @model OurService;


<form method="post">
    <div class="form-group">
        <label asp-for="Title"></label>
        <input class="form-control" asp-for="Title">
    </div>
    <div class="form-group">
        <label asp-for="Description"></label>
        <input class="form-control" asp-for="Description">
    </div>
    <div class="form-group">
        <label asp-for="ImgUrl"></label>
        <input class="form-control" asp-for="ImgUrl">
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>